# Generated by Django 3.2.2 on 2021-05-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurtureLabsDjangoApp', '0003_auto_20210508_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nurtureLabsDjangoApp.advisor')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
