# Generated by Django 3.2.2 on 2021-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurtureLabsDjangoApp', '0004_auto_20210508_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
